# Sadly, need to edit the toolchain generated by Altera for the fdt and libfdt 
# headers, because the syntax changed with the newer versions in the linux 
# libraries and gcc sees multiple declarations of the same functions
sed 's/_LIBFDT_H/LIBFDT_H/g' BuildUboot/uboot-socfpga/include/libfdt.h > BuildUboot/uboot-socfpga/include/libfdt.h 
sed 's/_FDT_H/FDT_H/g' BuildUboot/uboot-socfpga/include/fdt.h > BuildUboot/uboot-socfpga/include/fdt.h 

mkdir -p BuildUboot
bsp-create-settings --type spl --bsp-dir BuildUboot \
  --preloader-settings-dir GoldenTop/Work/hps_isw_handoff/standalone_hps_hps_0 \
  --settings BuildUboot/settings.bsp --set spl.boot.WATCHDOG_ENABLE false

make -C BuildUboot -j8
make -C BuildUboot uboot -j8

cat BuildUboot/preloader-mkpimage.bin BuildUboot/uboot-socfpga/u-boot.img > Outputs/boot-partition.img

quartus_cpf -c GoldenTop/Work/output_files/soc_system.sof Outputs/soc_system.rbf

sopc2dts --input GoldenTop/Work/standalone_hps.sopcinfo --output Outputs/socfpga.dts --type dts --board GoldenTop/HPS/cv_soc_devkit_ghrd/soc_system_board_info.xml --board GoldenTop/HPS/cv_soc_devkit_ghrd/hps_common_board_info.xml --bridge-removal all --clocks

dtc -f -I dts -O dtb -o Outputs/socfpga.dtb Outputs/socfpga.dts
