	standalone_hps u0 (
		.buttons_i_export                (<connected-to-buttons_i_export>),                // buttons_i.export
		.clk_clk                         (<connected-to-clk_clk>),                         //       clk.clk
		.dipsw_i_export                  (<connected-to-dipsw_i_export>),                  //   dipsw_i.export
		.h2f_bus_awid                    (<connected-to-h2f_bus_awid>),                    //   h2f_bus.awid
		.h2f_bus_awaddr                  (<connected-to-h2f_bus_awaddr>),                  //          .awaddr
		.h2f_bus_awlen                   (<connected-to-h2f_bus_awlen>),                   //          .awlen
		.h2f_bus_awsize                  (<connected-to-h2f_bus_awsize>),                  //          .awsize
		.h2f_bus_awburst                 (<connected-to-h2f_bus_awburst>),                 //          .awburst
		.h2f_bus_awlock                  (<connected-to-h2f_bus_awlock>),                  //          .awlock
		.h2f_bus_awcache                 (<connected-to-h2f_bus_awcache>),                 //          .awcache
		.h2f_bus_awprot                  (<connected-to-h2f_bus_awprot>),                  //          .awprot
		.h2f_bus_awqos                   (<connected-to-h2f_bus_awqos>),                   //          .awqos
		.h2f_bus_awvalid                 (<connected-to-h2f_bus_awvalid>),                 //          .awvalid
		.h2f_bus_awready                 (<connected-to-h2f_bus_awready>),                 //          .awready
		.h2f_bus_wdata                   (<connected-to-h2f_bus_wdata>),                   //          .wdata
		.h2f_bus_wstrb                   (<connected-to-h2f_bus_wstrb>),                   //          .wstrb
		.h2f_bus_wlast                   (<connected-to-h2f_bus_wlast>),                   //          .wlast
		.h2f_bus_wvalid                  (<connected-to-h2f_bus_wvalid>),                  //          .wvalid
		.h2f_bus_wready                  (<connected-to-h2f_bus_wready>),                  //          .wready
		.h2f_bus_bid                     (<connected-to-h2f_bus_bid>),                     //          .bid
		.h2f_bus_bresp                   (<connected-to-h2f_bus_bresp>),                   //          .bresp
		.h2f_bus_bvalid                  (<connected-to-h2f_bus_bvalid>),                  //          .bvalid
		.h2f_bus_bready                  (<connected-to-h2f_bus_bready>),                  //          .bready
		.h2f_bus_arid                    (<connected-to-h2f_bus_arid>),                    //          .arid
		.h2f_bus_araddr                  (<connected-to-h2f_bus_araddr>),                  //          .araddr
		.h2f_bus_arlen                   (<connected-to-h2f_bus_arlen>),                   //          .arlen
		.h2f_bus_arsize                  (<connected-to-h2f_bus_arsize>),                  //          .arsize
		.h2f_bus_arburst                 (<connected-to-h2f_bus_arburst>),                 //          .arburst
		.h2f_bus_arlock                  (<connected-to-h2f_bus_arlock>),                  //          .arlock
		.h2f_bus_arcache                 (<connected-to-h2f_bus_arcache>),                 //          .arcache
		.h2f_bus_arprot                  (<connected-to-h2f_bus_arprot>),                  //          .arprot
		.h2f_bus_arqos                   (<connected-to-h2f_bus_arqos>),                   //          .arqos
		.h2f_bus_arvalid                 (<connected-to-h2f_bus_arvalid>),                 //          .arvalid
		.h2f_bus_arready                 (<connected-to-h2f_bus_arready>),                 //          .arready
		.h2f_bus_rid                     (<connected-to-h2f_bus_rid>),                     //          .rid
		.h2f_bus_rdata                   (<connected-to-h2f_bus_rdata>),                   //          .rdata
		.h2f_bus_rresp                   (<connected-to-h2f_bus_rresp>),                   //          .rresp
		.h2f_bus_rlast                   (<connected-to-h2f_bus_rlast>),                   //          .rlast
		.h2f_bus_rvalid                  (<connected-to-h2f_bus_rvalid>),                  //          .rvalid
		.h2f_bus_rready                  (<connected-to-h2f_bus_rready>),                  //          .rready
		.h2f_reset_reset_n               (<connected-to-h2f_reset_reset_n>),               // h2f_reset.reset_n
		.hps_io_hps_io_emac1_inst_TX_CLK (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>), //    hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0   (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),   //          .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1   (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),   //          .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2   (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),   //          .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3   (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),   //          .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0   (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),   //          .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO   (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),   //          .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC    (<connected-to-hps_io_hps_io_emac1_inst_MDC>),    //          .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>), //          .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>), //          .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>), //          .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1   (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),   //          .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2   (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),   //          .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3   (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),   //          .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_qspi_inst_IO0     (<connected-to-hps_io_hps_io_qspi_inst_IO0>),     //          .hps_io_qspi_inst_IO0
		.hps_io_hps_io_qspi_inst_IO1     (<connected-to-hps_io_hps_io_qspi_inst_IO1>),     //          .hps_io_qspi_inst_IO1
		.hps_io_hps_io_qspi_inst_IO2     (<connected-to-hps_io_hps_io_qspi_inst_IO2>),     //          .hps_io_qspi_inst_IO2
		.hps_io_hps_io_qspi_inst_IO3     (<connected-to-hps_io_hps_io_qspi_inst_IO3>),     //          .hps_io_qspi_inst_IO3
		.hps_io_hps_io_qspi_inst_SS0     (<connected-to-hps_io_hps_io_qspi_inst_SS0>),     //          .hps_io_qspi_inst_SS0
		.hps_io_hps_io_qspi_inst_CLK     (<connected-to-hps_io_hps_io_qspi_inst_CLK>),     //          .hps_io_qspi_inst_CLK
		.hps_io_hps_io_sdio_inst_CMD     (<connected-to-hps_io_hps_io_sdio_inst_CMD>),     //          .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0      (<connected-to-hps_io_hps_io_sdio_inst_D0>),      //          .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1      (<connected-to-hps_io_hps_io_sdio_inst_D1>),      //          .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK     (<connected-to-hps_io_hps_io_sdio_inst_CLK>),     //          .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2      (<connected-to-hps_io_hps_io_sdio_inst_D2>),      //          .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3      (<connected-to-hps_io_hps_io_sdio_inst_D3>),      //          .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0      (<connected-to-hps_io_hps_io_usb1_inst_D0>),      //          .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1      (<connected-to-hps_io_hps_io_usb1_inst_D1>),      //          .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2      (<connected-to-hps_io_hps_io_usb1_inst_D2>),      //          .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3      (<connected-to-hps_io_hps_io_usb1_inst_D3>),      //          .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4      (<connected-to-hps_io_hps_io_usb1_inst_D4>),      //          .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5      (<connected-to-hps_io_hps_io_usb1_inst_D5>),      //          .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6      (<connected-to-hps_io_hps_io_usb1_inst_D6>),      //          .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7      (<connected-to-hps_io_hps_io_usb1_inst_D7>),      //          .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK     (<connected-to-hps_io_hps_io_usb1_inst_CLK>),     //          .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP     (<connected-to-hps_io_hps_io_usb1_inst_STP>),     //          .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR     (<connected-to-hps_io_hps_io_usb1_inst_DIR>),     //          .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT     (<connected-to-hps_io_hps_io_usb1_inst_NXT>),     //          .hps_io_usb1_inst_NXT
		.hps_io_hps_io_spim0_inst_CLK    (<connected-to-hps_io_hps_io_spim0_inst_CLK>),    //          .hps_io_spim0_inst_CLK
		.hps_io_hps_io_spim0_inst_MOSI   (<connected-to-hps_io_hps_io_spim0_inst_MOSI>),   //          .hps_io_spim0_inst_MOSI
		.hps_io_hps_io_spim0_inst_MISO   (<connected-to-hps_io_hps_io_spim0_inst_MISO>),   //          .hps_io_spim0_inst_MISO
		.hps_io_hps_io_spim0_inst_SS0    (<connected-to-hps_io_hps_io_spim0_inst_SS0>),    //          .hps_io_spim0_inst_SS0
		.hps_io_hps_io_uart0_inst_RX     (<connected-to-hps_io_hps_io_uart0_inst_RX>),     //          .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX     (<connected-to-hps_io_hps_io_uart0_inst_TX>),     //          .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA     (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),     //          .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL     (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),     //          .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_can0_inst_RX      (<connected-to-hps_io_hps_io_can0_inst_RX>),      //          .hps_io_can0_inst_RX
		.hps_io_hps_io_can0_inst_TX      (<connected-to-hps_io_hps_io_can0_inst_TX>),      //          .hps_io_can0_inst_TX
		.hps_io_hps_io_trace_inst_CLK    (<connected-to-hps_io_hps_io_trace_inst_CLK>),    //          .hps_io_trace_inst_CLK
		.hps_io_hps_io_trace_inst_D0     (<connected-to-hps_io_hps_io_trace_inst_D0>),     //          .hps_io_trace_inst_D0
		.hps_io_hps_io_trace_inst_D1     (<connected-to-hps_io_hps_io_trace_inst_D1>),     //          .hps_io_trace_inst_D1
		.hps_io_hps_io_trace_inst_D2     (<connected-to-hps_io_hps_io_trace_inst_D2>),     //          .hps_io_trace_inst_D2
		.hps_io_hps_io_trace_inst_D3     (<connected-to-hps_io_hps_io_trace_inst_D3>),     //          .hps_io_trace_inst_D3
		.hps_io_hps_io_trace_inst_D4     (<connected-to-hps_io_hps_io_trace_inst_D4>),     //          .hps_io_trace_inst_D4
		.hps_io_hps_io_trace_inst_D5     (<connected-to-hps_io_hps_io_trace_inst_D5>),     //          .hps_io_trace_inst_D5
		.hps_io_hps_io_trace_inst_D6     (<connected-to-hps_io_hps_io_trace_inst_D6>),     //          .hps_io_trace_inst_D6
		.hps_io_hps_io_trace_inst_D7     (<connected-to-hps_io_hps_io_trace_inst_D7>),     //          .hps_io_trace_inst_D7
		.leds_o_export                   (<connected-to-leds_o_export>),                   //    leds_o.export
		.memory_mem_a                    (<connected-to-memory_mem_a>),                    //    memory.mem_a
		.memory_mem_ba                   (<connected-to-memory_mem_ba>),                   //          .mem_ba
		.memory_mem_ck                   (<connected-to-memory_mem_ck>),                   //          .mem_ck
		.memory_mem_ck_n                 (<connected-to-memory_mem_ck_n>),                 //          .mem_ck_n
		.memory_mem_cke                  (<connected-to-memory_mem_cke>),                  //          .mem_cke
		.memory_mem_cs_n                 (<connected-to-memory_mem_cs_n>),                 //          .mem_cs_n
		.memory_mem_ras_n                (<connected-to-memory_mem_ras_n>),                //          .mem_ras_n
		.memory_mem_cas_n                (<connected-to-memory_mem_cas_n>),                //          .mem_cas_n
		.memory_mem_we_n                 (<connected-to-memory_mem_we_n>),                 //          .mem_we_n
		.memory_mem_reset_n              (<connected-to-memory_mem_reset_n>),              //          .mem_reset_n
		.memory_mem_dq                   (<connected-to-memory_mem_dq>),                   //          .mem_dq
		.memory_mem_dqs                  (<connected-to-memory_mem_dqs>),                  //          .mem_dqs
		.memory_mem_dqs_n                (<connected-to-memory_mem_dqs_n>),                //          .mem_dqs_n
		.memory_mem_odt                  (<connected-to-memory_mem_odt>),                  //          .mem_odt
		.memory_mem_dm                   (<connected-to-memory_mem_dm>),                   //          .mem_dm
		.memory_oct_rzqin                (<connected-to-memory_oct_rzqin>),                //          .oct_rzqin
		.reset_reset_n                   (<connected-to-reset_reset_n>)                    //     reset.reset_n
	);

